import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly placeholder = 'https://via.placeholder.com/400x300?text=Product';

  private readonly categories: Category[] = [
    { id: 1, name: 'Smartphones' },
    { id: 2, name: 'Laptops' },
    { id: 3, name: 'Headphones' },
    { id: 4, name: 'Tablets' },
  ];

  private readonly products: Product[] = [
    // ---------------- Smartphones (categoryId: 1) ----------------
    {
      id: 101,
      categoryId: 1,
      name: 'Apple iPhone 15 128GB (Black)',
      description: 'iPhone 15 with a bright OLED display and strong performance. Great camera and smooth iOS experience.',
      price: 385730,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h1d/hfc/86303745998878.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-iphone-15-128gb-chernyi-113137790/',
    },
    {
      id: 102,
      categoryId: 1,
      name: 'Apple iPhone 15 128GB Dual eSIM (Green)',
      description: 'A modern iPhone with Dynamic Island and a powerful chip. Comfortable for everyday use and content.',
      price: 392835,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/haa/had/86594359197726.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-iphone-15-128gb-dual-esim-zelenyi-121693378/',
    },
    {
      id: 103,
      categoryId: 1,
      name: 'Apple iPhone 15 128GB Dual eSIM (Pink)',
      description: 'Stylish iPhone 15 in pink color. Excellent camera quality and stable performance.',
      price: 420362,
      rating: 4.9,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/hf3/h03/86594352644126.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-iphone-15-128gb-dual-esim-rozovyi-121692808/',
    },
    {
      id: 104,
      categoryId: 1,
      name: 'Samsung Galaxy S24 5G 8/256 (Gray)',
      description: 'Compact flagship with a smooth AMOLED screen and fast Android experience. Solid cameras and 5G support.',
      price: 399990,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h05/hca/84961127989278.png?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/samsung-galaxy-s24-5g-8-gb-256-gb-seryi-116040863/',
    },
    {
      id: 105,
      categoryId: 1,
      name: 'Xiaomi Redmi Note 13 Pro 4G NFC 8/256 (Green)',
      description: 'Great value smartphone with a large AMOLED display. Good daily performance and modern design.',
      price: 169990,
      rating: 4.6,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h9b/h96/84941911949342.png?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/xiaomi-redmi-note-13-pro-4g-nfc-8-gb-256-gb-zelenyi-115966726/',
    },

    // ---------------- Laptops (categoryId: 2) ----------------
    {
      id: 201,
      categoryId: 2,
      name: 'Apple MacBook Air 13 M3 (2024) 8GB/512GB',
      description: 'Light and fast ultrabook for study and work. Great battery life and macOS ecosystem.',
      price: 599990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/ha2/h71/85669725470750.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2024-13-6-8-gb-ssd-512-gb-macos-mrxw3ru-a-118170293/',
    },
    {
      id: 202,
      categoryId: 2,
      name: 'Apple MacBook Air 13 M3 (2024) 16GB/256GB',
      description: 'More RAM for multitasking. Perfect for coding, browsing, and lightweight creative tasks.',
      price: 679990,
      rating: 4.9,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/p22/p34/14343715.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2024-13-6-16-gb-ssd-256-gb-macos-mc8g4-131761862/',
    },
    {
      id: 203,
      categoryId: 2,
      name: 'Lenovo Legion 5 16IRX9 (Gaming)',
      description: 'Powerful laptop for gaming and heavy tasks. High refresh screen and strong GPU options.',
      price: 799990,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h3d/h09/85605452283934.png?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/lenovo-legion-5-16-16-gb-ssd-1024-gb-dos-16irx9-83dg008krk-117986888/',
    },
    {
      id: 204,
      categoryId: 2,
      name: 'ASUS Vivobook 15 16GB/512GB',
      description: 'Good everyday laptop for study and office. Comfortable keyboard and practical design.',
      price: 329990,
      rating: 4.6,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h94/h71/85257477652510.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/asus-vivobook-15-15-6-16-gb-ssd-512-gb-bez-os-x1504za-bq274-90nb1022-m00ca0-116912940/',
    },
    {
      id: 205,
      categoryId: 2,
      name: 'HP Pavilion 15 (16GB/512GB, Win11)',
      description: 'Balanced laptop for work and learning. Stable performance, IPS screen, and Windows 11.',
      price: 349990,
      rating: 4.5,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h2f/hdd/66793199796254.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/hp-pavilion-15-6-16-gb-ssd-512-gb-win-11-15-eg2020ci-6g811ea-108001774/',
    },

    // ---------------- Headphones (categoryId: 3) ----------------
    {
      id: 301,
      categoryId: 3,
      name: 'Sony WH-1000XM5 (Black)',
      description: 'Top ANC headphones with premium sound. Excellent for travel and focus.',
      price: 189990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h9c/h23/65099684020254.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/naushniki-sony-wh-1000xm5-chernyi-105259822/',
    },
    {
      id: 302,
      categoryId: 3,
      name: 'Sony WH-1000XM5 (Silver)',
      description: 'Comfortable fit and strong noise cancelling. Great wireless audio quality.',
      price: 189990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h22/h56/64476310306846.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/naushniki-sony-wh-1000xm5-serebristyi-105577599/',
    },
    {
      id: 303,
      categoryId: 3,
      name: 'Apple AirPods Pro 2 (MagSafe)',
      description: 'Compact TWS with ANC and transparency mode. Works perfectly inside Apple ecosystem.',
      price: 129990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/ha3/h07/84108189630494.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-generation-with-wireless-magsafe-charging-case-belyi-113677582/',
    },
    {
      id: 304,
      categoryId: 3,
      name: 'Samsung Galaxy Buds2 Pro (White)',
      description: 'TWS with rich sound and good ANC. Great pair for Samsung phones.',
      price: 79990,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h69/h44/64496879435806.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/naushniki-samsung-galaxy-buds2-pro-belyi-106128764/',
    },
    {
      id: 305,
      categoryId: 3,
      name: 'Bose QuietComfort 45 (Black)',
      description: 'Comfort-first ANC headphones. Smooth sound and great for long listening sessions.',
      price: 169990,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/hba/h67/64374646538270.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/naushniki-bose-quietcomfort-45-chernyi-102978612/',
    },

    // ---------------- Tablets (categoryId: 4) ----------------
    {
      id: 401,
      categoryId: 4,
      name: 'Apple iPad 10.9 (2022) Wi-Fi 64GB (Silver)',
      description: 'Great tablet for media, notes, and study. Smooth performance and nice screen.',
      price: 229990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h5d/h3c/64865317584926.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-ipad-10-9-2022-wi-fi-10-9-djuim-4-gb-64-gb-serebristyi-107264764/',
    },
    {
      id: 402,
      categoryId: 4,
      name: 'Apple iPad 10.9 (2022) Wi-Fi + 5G 64GB (Blue)',
      description: 'Same iPad with mobile internet. Useful for travel and always-online workflows.',
      price: 279990,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h22/hc4/64871997145118.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-ipad-2022-10-9-wi-fi-5g-10-9-djuim-4-gb-64-gb-sinii-107269815/',
    },
    {
      id: 403,
      categoryId: 4,
      name: 'Xiaomi Pad 6 11" 8/256 (Blue)',
      description: 'Value tablet with big screen and solid performance. Great for video and multitasking.',
      price: 199990,
      rating: 4.6,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h53/h7e/82746416398366.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/xiaomi-pad-6-11-djuim-8-gb-256-gb-goluboi-112468565/',
    },
    {
      id: 404,
      categoryId: 4,
      name: 'Huawei MatePad 11 Wi-Fi 10.9" 6/128 (Gray)',
      description: 'Tablet for study and entertainment. Good display and comfortable size.',
      price: 259890,
      rating: 4.7,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/h6f/h8f/64353836171294.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/huawei-matepad-11-wi-fi-10-9-djuim-6-gb-128-gb-seryi-102420544/',
    },
    {
      id: 405,
      categoryId: 4,
      name: 'Apple iPad Air 11 (2024) Wi-Fi 128GB (Beige)',
      description: 'Powerful iPad Air with M2-level performance. Great for study, work, and creativity.',
      price: 499990,
      rating: 4.8,
      likes: 0,
      image: 'https://resources.cdn-kaspi.kz/img/m/p/he0/h33/86106953678878.jpg?format=gallery-medium',
      images: [this.placeholder, this.placeholder, this.placeholder],
      link: 'https://kaspi.kz/shop/p/apple-ipad-air-11-2024-wi-fi-11-djuim-8-gb-128-gb-svetlo-bezhevyi-119778076/',
    },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getProductsByCategory(categoryId: number): Product[] {
    return this.products.filter(p => p.categoryId === categoryId).map(p => ({ ...p }));
  }
}